#spring.datasource.url =jdbc:mysql://localhost:3306/couponify?useSSL=false&serverTimezone=UTC
#spring.datasource.username= root
#spring.datasource.password = RadisysRadisys@2895
## Hibernate ddl auto (create, create-drop, validate, update)
#spring.jpa.hibernate.ddl-auto = update
#app.jwt-secret = JWTSecretKey
#app.jwt-expiration-millisecond = 604800000
  #60000 1min
logging:
  level:
    org:
      springframework:
        security: DEBUG
spring:
    datasource:
        url: jdbc:mysql://localhost:3306/couponify?useSSL=false&serverTimezone=UTC
        username: root
        password: RadisysRadisys@2895

    jpa:
      hibernate:
          ddl-auto: update

    security:
      oauth2:
        client:
          registration:
            google:
              clientId: 511594798439-jv2qcm3ffhh337bvnbds6c8ilt0t82fj.apps.googleusercontent.com
              clientSecret: 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
              redirectUri: "{baseUrl}/oauth2/callback/{registrationId}"
              scope:
                - email
                - profile

            facebook:
              clientId: 2889599231185507
              clientSecret: 0e9ef64fd914c54504425025f4b6a985
              redirectUri: "{baseUrl}/oauth2/callback/{registrationId}"
              scope:
                  - email
                  - public_profile

#            github:
#              clientId: 986e170a056c1dd1
#             redirectUri: "{baseUrl}/oauth2/callback/{registrationId}"
#              scope:
#                - email
#                - profile

            provider:
              facebook:
                authorizationUri: https://www.facebook.com/v3.0/dialog/oauth
                tokenUri: https://graph.facebook.com/v3.0/oauth/access_token
                userInfoUri: https://graph.facebook.com/v3.0/me?fields=id,first_name,middle_name,last_name,name,email,verified,is_verified,picture.width(250).height(250)

app:
    auth:
      tokenSecret: JWTSecretKey
      tokenExpirationMsec: 604800000

    cors:
      allowedOrigin: http://localhost:3000

    oauth2:
      authorizedRedirectUris:
        - http://localhost:8080/oauth2/redirect
        - http://localhost:8080/redirect-uri
        - myandroidapp://oauth2/redirect
        - myiosapp://oauth2/redirect



